### ISSUE TITLE
[ISSUE] Bioluminescence

### ISSUE THREAD

**Issue by SensualNighthawk** [Decollates/MOD-POT-Nyctatyrannus#14]
```
Bioluminescence Issue
```
When using the Default Nycta skin, selecting any bioluminescence color does not rotate through a rainbow scheme when using the Cuddle emote. Green, flashes through green and blue. Red, flashes through red, orange and yellow. Blue flashes blue and green, a tiny bit of yellow/orange. Purple gives blue, purple, also a brief flash of yellow/orange. Yellow, gives flashes of red, orange, and yellow.

```
To Reproduce
```
1. Go to 'Default Nycta Skin'
2. Click on 'Any of the bioluminescence colors'
3. Scroll down to 'Begin Shed'

```
https://www.youtube.com/watch?v=B1L-kmboKX4
```
If applicable, add screenshots to help explain your problem. The more evidence describing the issue, the better.

**Comment by Decollates** [comment]
This is intentional - the calls will have the bioluminescence go through a few different value ranges that can cause different colors to appear depending on what the selected color for the bioluminescence is. Different colors will have different effects. It was never the purpose for the effect to give a rainbow effect.
